let recipesItems = [
    {
        id: 1,
        image: 'image/CT1.jpg',
        title: 'Cách làm bánh phục linh bằng khuôn đơn giản tại nhà',
        summary: 'Bánh phục linh là món bánh mà có lẽ là tuổi thơ của nhiều người, tuy món bánh chỉ làm từ bột đơn giản nhưng chứa đựng biết bao nhiêu kỷ niệm thời thơ ấu. Hãy vào bếp học làm bánh phục linh này cùng May&May nhé.',
        recipes: [
            'Bột năng: 200g',
            'Nước cốt dừa: 150ml',
            'Đường: 100g',
           ' Nước cốt lá dứa: 2 muỗng canh',
            'Lá dứa: 5 lá',
        ],
        tutorials: [
            'Bước 1: Rang bột',
            '- Đầu tiên bạn cho bột và lá dứa vào một cái chảo, lưu ý là lá dứa phải được khô ráo và cắt thành từng khúc nhỏ khoảng 2 đốt lóng tay. Sau đó bật lên rang bột với lửa nhỏ, đảo đều tay để bột năng được chín đều ngon hơn.',
            '- Để biết bột chín hay chưa thì bạn bóp thử cọng lá dứa nếu nó giòn, dễ gãy thì bột đã chín và bạn nhắc khỏi bếp và để cho bột nguội.',
            'Bước 2: Nấu nước cốt dừa',
            '- Cho đường vào một cái nồi, tiếp theo là cho nước cốt dừa vào nấu cho đường tan và sệt lại, sau khi thấy nước cốt sánh lại thì bạn múc ½ lượng nước cốt trong nồi ra ngoài một cái bát để làm phần bánh màu trắng.',
            '- Phần nước cốt còn lại trong nồi thì bạn cho nước lá dứa vào nấu cùng, nấu cho nước sánh lại thì tắt bếp cho ra bát. Lá dứa khi bạn xay lấy nước thì bạn đợi cho nước lắng xuống lấy phần nước cốt đậm như thế màu bột sẽ được đậm hơn.',
            'Bước 3: Trộn bột và ép khuôn',
            '- Bạn chia bột thành 2 phần tô bằng nhau nhớ rây bỏ lá dứa ra và chừa lại một ít để áo khuôn, sau đó bạn cho từ từ phần nước cốt dừa vào tô bột màu trắng, cho từng muỗng nước cốt dừa vào, vừa cho vừa dùng tay trộn đều bột, nếu vắt bột lại thành một khối và khi bóp vào bột tan đều ra là bột đã đạt. Và phần màu xanh bạn cũng làm tương tự như vậy.',
            '- Phủ một lớp bột lên khuôn rồi đập nhẹ xuống bàn cho bột rớt ra hết, sau đó cho phần bột trộn với nước cốt dừa vào khuôn, dùng tay ấn chặt để bánh được dẻ và không bị vỡ khi mở khuôn. Đập nhẹ khuôn xuống mặt bạn cho bánh rớt ra, tiếp tục làm cho hết phần bột còn lại.',
            '- Sau khi ấn khuôn xong hết thì bạn xếp bánh ra một cái mâm để cho bánh được ráo và chắc hơn và sau đó thì bạn có thể thưởng thức được ngay. Bánh thơm béo mùa của lá dứa là nước cốt dừa khi ăn vào thì tan ngay trong miệng, ăn bánh này nhâm nhi thêm một tách trà thì còn gì bằng.',
        ]
    },
    {
        id: 2,
        image: 'image/CT2.webp',
        title: 'Cách làm bánh Waffle đơn giản ngay tại nhà',
        summary: 'Waffle là một loại bánh bổ biến ở phương Tây. Với kết cấu mềm, dai dai thơm thơm của sữa trứng và không bị quá ngọt. Hãy cùng May&May thực hiện cách làm bánh waffle này nhé.',
        recipes: [
            'Bột mì: 300gr',
            'Bột nổi: 2 mcf',
            'Muối: ½ mcf',
            'Đường: 40g',
            'Sữa tươi: 300ml',
            'Lòng đỏ trứng gà: 2 trứng',
            'Lòng trắng trứng gà: 4 trứng',
            'Đường: 60g',
            'Bơ: 50gr',
            'Tinh chất vani: 1 mcf',
        ],
        tutorials: [
            'Bước 1: Trộn tất cả nguyên liệu khô gồm bột mì, bột nổi, muối, 40g đường lại với nhau rồi dùng rây rây cho hỗn hợp bột khô được mịn không bị vón cục',
            'Bước 2: Đun chảy bơ sau đó chuẩn bị một cái tô cho lòng đỏ trứng gà và sữa vào đánh đều, cho tiếp bơ tan chảy và vani vào khuấy đều. Tiếp theo cho hỗn hợp bột khô vừa rây khi nảy vào và trộn đều lên, có thể lược qua rây một lần cho hỗn hợp được mịn hơn',
            'Bước 3: Tiếp theo bạn chuẩn bị một cái tô lớn cho lòng trắng trứng và đường vào đánh cho đến khi bông cứng. Rồi trộn phần lòng trắng vào hỗn hợp bột lòng đỏ dùng cây vét trộn đều từ dưới đáy lên. Cho hỗn hợp bột vào trong ngăn mát nghỉ khoảng 1 giờ hoặc nếu có thời gian thì để lâu hơn khi ăn rồi hãy nướng.',
            'Bước 4: Đem bánh đi nướng, đầu tiên bạn làm nóng khuôn trước sau đó phết một lớp bơ lên khuôn rồi cho bột vào gần đầy khuôn và nướng trong khoảng 7-10 phút là bánh chín vàng.',
        ]
    },
    {
        id: 3,
        image: 'image/CT3.webp',
        title: 'Cách làm bánh flan SIÊU ĐƠN GIẢN tại nhà',
        summary: 'Cách làm bánh flan thơm ngon, mềm mịn tại nhà cũng những nguyên liệu vô cùng đơn giản dễ dàng làm ra một món tráng miệng được nhiều người ưa thích. Sau đây May&May sẽ gửi đến bạn công thức để làm bánh flan siêu ngon',
        recipes: [
            `6 quả trứng gà`,
            `250ml sữa tươi`,
            `1 hộp sữa đặc có đường`,
            `100g đường`,
            `Vani 2 ống`,
            `Nước lọc`,
            `1/2 quả chanh`,
            `Khuôn đựng (cốc hoặc hộp)`,
        ],
        tutorials: [
            'Bước 1: Cách làm caramel: Cho 70g đường với 100ml nước lọc, cho lên bếp đun lửa vừa từ 5-7 phút khi thấy hỗn hợp sôi thì vắt nửa lát chanh vào và đun đến khi hỗn hợp chuyển sang màu cánh gián là được (chú ý không nên khuấy trong lúc nấu vì như thế sẽ bị lại đường ).',
            'Sau đó cho hỗn hợp ra cốc hoặc khuôn tráng mỏng một lớp đường rồi để vào ngăn mát tủ lạnh.',
            'Bước 2: Cách làm bánh flan:',
            '- Tách lấy 4 lòng đỏ trứng gà, và 2 quả trứng lấy cả lòng trắng và lòng đỏ, cho thêm 30g đường và 2 ống vani vào khuấy nhẹ theo một chiều ( không được đánh bông ) cho đến khi đường tan hòa huyện vào nhau',
            '- Đổ sữa tươi vào nồi đun lửa nhỏ cho đển khi sữa sôi tiêm rồi tắt bếp ( không được để sôi lớn vì như thế sẽ làm cho trứng bị chín ) cho sữa đặc vào khuấy điều',
            '- Cho từ từ sữa vào hỗn hợp trứng, vừa đổ vào vừa khuấy theo một chiều cho huyện vào nhau có màu vàng nhạt. Sau đó lọc hỗn hợp qua một cái rây 1 đến 2 lần để cho hỗn hợp được mịn hơn',
            '- Múc hỗn hợp trứng sữa vào cốc đã tráng một lớp caramen, đổ đầy cốc và đậy nắp lại.',
            '- Sắp các cốc bánh vào xửng hấp và mang đi hấp cách thủy từ 30-40 phút. Hấp với lửa nhỏ nhất cứ 10 phút thì mở nắp một lần để nước không đọng lại trên mặt bánh (có thể hấp bánh bằng nồi cơm điện )',
            '- Để kiểm tra bánh chín chưa chỉ cần lấy cây tăm cắm xuống nếu thấy không dính thì đã chín. Nhắc nồi xuống lấy bánh ra mở nắp và để bánh thật nguội rồi mới cho vào ngăn mát tủ lạnh.',
        ]
    },
    {
        id: 4,
        image: 'image/CT4.jpg',
        title: 'Cách làm bánh trung thu ngàn lớp Đài Loan lạ đẹp mắt',
        summary: 'Cách làm bánh trung thu ngàn lớp đơn giản tại nhà mà không mất quá nhiều thời gian. Nào hãy cùng vào bếp làm món bánh trung thu ngàn lớp với May&May nhé.',
        recipes: [
            `Khoai môn: 400g`,
            `Muối: 2g`,
            `Nước 200ml`,
            `Đường: 100g`,
            `Nước: 100ml`,
            `Sữa đặc: 100g`,
            `Tinh bột bắp: 10g`,
            `Nước: 30ml`,
            `Tinh chất khoai môn: 1 ít`,
            `Dầu dừa: 40g`,
            `Lòng đỏ trứng muối: 12 cái`,
            `Rượu trắng: 50ml`,
            `Nước: 110ml`,
            `Đường: 40g`,
            `Muối: 3g`,
            `Bơ lạt: 70g`,
            `Bột mì đa dụng: 200g`,
            `Phần bột dầu`,
            `Bột mì đa dung: 130g`,
            `Dầu ăn: 55g`,
            `Lòng đỏ: 1 cái`,
            `Mè: một ít`,
        ],
        tutorials: [
            'Bước 1: Phần nhân bánh',
            '- Khoai môn mua về bạn sơ chế cho sạch rồi cắt thành những miếng nhỏ để nấu cho mau mềm.',
            '- Cho khoai vào nồi, thêm vào 200ml nước và 2 g muối vào. Bắt lên bếp nấu lửa trung bình khoảng 8-10 phút cho khoai chín mềm.',
            '- Nhắc khỏi bếp rồi đậy kín lại. Trong lúc này thì bạn đi nấu nước đường. Cho vào chảo 100ml nước và 100g đường, bắt lên bếp đun cho tan đường.',
            '- Sau đó cho nước đường vừa nấu và 100g sữa đặc vào nồi khoai môn hấp rồi dùng máy xay xay nhuyễn.',
            '- Lượt hỗn hợp khoai qua rây cho vào một cái nồi khác. Pha bột bắp với nước, khuấy tan rồi cho lại vào chảo nhân, khuấy đều hỗn hợp lên. Nếu muốn màu đậm hơn thì cho thêm một ít tinh chất vanila vào.',
            '- Bắt nồi nhân lên bếp sên với lửa lớn, khuấy liên tục cho đều tay. Đến khi thấy sôi thì hạ xuống lửa trung bình và vẫn khuấy đều tay. ',
            '- Lúc này bạn cho ½ lượng dầu dừa vào khuấy cho hòa quyện rồi mới cho tiếp phần còn lại vào. Như vậy phần nhân mới không bị tách dầu. Và tiếp tục khuấy đều khoảng 20 phút cho đến khi nhân khô dẻo, sờ thử tay vào mà không bị dính tay thì đạt.',
            '- Cho nhân ra một cái bát, đậy kín và để nguội.',
            '- Tiếp theo thì đi hấp trứng muối. Bạn rửa trứng muối với rượu trắng rồi cho vào xửng đem đi hấp hoặc có thể nướng. Thời gian hấp khoảng 10 phút.'+
            '- Sau đó bạn đi chia nhân thành 12 phần bằng nhau khoảng 45g cho 1 viên. Rồi cho trứng muối vào giữa, vo lại cho tròn.',
            'Bước 2: Phần bột nước',
            '- Chuẩn bị một cái bát, cho nước, muối, đường và bơ melt chảy khuấy đều cho tan hết đường. Sau đó cho bột vào và trộn đều bột lên cho chất lỏng được thấm vào bột.',
            '- Dùng màng bọc đậy kín và để bột nghỉ 15 phút. Sau 15 phút thì đem bột ra nhồi và đập bột, với cách này một sẽ nhanh mịn và ngon. Tiếp tục để bột nghỉ khoảng 1 giờ.',
            'Bước 3: Phần bột dầu',
            '- Cho vào bát 55g dầu và 130g bột mì trộn đều cho dầu và bột đều với nhau. Sau đó chia bột thành 12 phần bằng nhau khoảng 15g.',
            'Bước 4: Chia bột và gói bánh',
            '- Bột nước sau khi nghĩ xong thì bạn đem ra chia thành 12 phần bằng nhau, khoảng 35g/ viên. Vo tròn viên bột lại và bắt đầu đi cán.',
            '- Viên nào vo trước thì cán trước. Ấn dẹp viên bột nước rồi cho viên bột dầu vào giữa, túm bột lại sao cho kín mí bột là được. Lần lượt làm cho hết phần bột còn lại rồi mới đi cán.',
            '- Cho viên bột đầu tiên ra bàn, dùng cây cán bột cán theo chiều dọc và độ dày khoảng 1-2mm.',
            '- Sau đó, gấp miếng bột lại làm 3 và xoay miếng bột lại tiếp tục cán tương tự và gấp làm 3 một lần nữa. Vậy là bột của chúng ta đã có chín lớp và bạn tiếp tục làm cho hết bột.',
            '- Khi cán bột xong thì để bột nghỉ 15 phút để bột không bị co giãn khi cán.',
            '- Sau 15 phút cho viên bột ra bàn cán mỏng rồi cho viên nhân vào giữa, túm bột lại cho tròn đều.',
            '- Cho bánh lên khay rồi phết mỏng một lớp trứng gà lên mặt bánh. Sau đó bạn cho một ít mè đen lên trên mặt bánh rồi đem nướng.',
            'Bước 5: Nướng bánh',
            '- Làm nóng lò ở nhiệt độ khoảng 190 độ C 15 phút.',
            '- Cho bánh vào nướng khoang 20-22 phút, 190 độ C tùy vào nhiệt độ lò của từng nhà.',
            '<- Thấy mặt bánh hơi vàng thì lấy ra và để nguội. Bánh cho vào hộp kín thì có thể bảo quản được 4-5 ngày với nhiệt độ thường. Hoặc có thể cho vào ngăn mát tủ lạnh, khi ăn chỉ cần hâm nóng lại là dùng được.',
        ]
    },
    {
        id: 5,
        image: 'image/CT5.jpeg',
        title: 'Cách Làm Bánh Flan Rau Câu Trái Dừa',
        summary: 'Cách làm bánh flan rau câu trái dừa là sự kết hợp thật mới mẻ của thạch lá dứa và bánh flan. May&May sẽ gửi đến bạn công thức làm bánh cực kì đơn giản và để làm một món tráng miệng thơm ngon tại nhà nhé!',
        recipes: [
            'Dừa xiêm: 1 quả ( cơm dừa không quá già hay quá mềm)',
            'Trứng gà: 2 quả',
            'Sữa tươi: 400ml',
            'Lá dứa: 10g',
            'Đường cát: 40g',
            'Bột rau câu: 25g`',
            'Vani: 15g',
        ],
        tutorials: [
            'Bước 1: Làm phần rau câu bên trong trái dừa',
            '- Dùng dao chặt bỏ phần vỏ cứng bên ngoài vỏ dừa, gọt sạch vỏ lụa rồi rửa lại cho trái dừa được trắng. Tiếp đến, bạn khoét một lỗ nhỏ trên đầu trái dừa với đường kính khoảng 2cm, sau đó đổ hết phần nước dừa bên trong ra ngoài.',
            '- Lá dứa rửa sạch, cắt khúc, cho vào máy xay sinh tố thêm một it nước, xay nhuyễn. Lọc lá dứa đã xay ra một cái rây để lấy nước cốt.',
            '- Bắt một cái nồi lên bếp, lần lượt cho nước cốt lá dứa và nước dừa vào bắt lên bếp đun sôi, cho 20g đường và 20g bột rau câu vào một cái bát trộn đều, rồi cho từ từ vào nước lá dứa đang sôi vừa cho vừa khuấy đều tay cho hỗn hợp hòa tan. Đến khi sôi lên lại thì tắt bếp đổ vào khuôn và để nguội, khi rau câu đã đông cứng thì cho vào ngăn mát tủ lạnh',
            'Bước 2: Làm flan trứng',
            '- Lấy một chiếc âu, cho sữa tươi, 5g bột rau câu đường, 20g đường và trứng vào khuấy đều cho hỗn hợp quyện vào nhau, sau đó lọc hỗn hợp qua một cái rây để cho bánh được mịn hơn.',
            '- Cho hỗn hợp lên bếp thêm vani vào (không có cũng không sao) đun đến khi thấy sôi lăn tăn thì tắt bếp.'+
            'Bước 3: Hấp bánh flan rau câu trái dừa',
            '- Lấy rau câu lá dứa trong tủ lạnh ra, cắt thành hình hạt lựu dài ngắn tùy sở thích, rồi cho vào trong trái dừa, sau đó đổ hỗn hợp flan trứng vào bên trong trái dừa cho ngập các thạch rau câu (chú ý không đổ quá đầy vì khi hấp có thể làm bánh trào ra)',
            '-  Đem trái dừa đi hấp cách thủy khoảng 90 phút là bánh sẽ chín. Lấy ra để nguội rồi cho vào ngăn mát tủ lạnh. Khi nào dùng thì lấy ra cắt bánh thành những miếng nhỏ múi cao rồi thưởng thức.',
        ]
    },
    {
        id: 6,
        image: 'image/CT6.jpeg',
        title: 'Cách làm panna cotta đơn giản tại nhà',
        summary: 'Panna cotta là món ăn mà có lẽ không quá xa lạ đối với mấy bạn trẻ tuổi teen rồi. Cùng May&MAy thực hiện cách làm panna cotta tại nhà nhé.',
        recipes: [
            'Sữa tươi không đường: 250ml',
            'Whipping cream: 250ml',
            'Đường: 60g',
            'Gelatin: 6-8g',
            'Vanilla: 5ml ( không có cũng không sao)',
            'Mứt trái cây tùy sở thích'
        ],
        tutorials: [
            'Bước 1: Làm panna cotta',
            '- Đầu tiên bạn ngâm 8g gelatin lá với nước lạnh, sau đó cho kem tươi sữa tươi vào nồi và 60g đường. Bắt lên bếp đun với lửa nhỏ.',
            '- Trong lúc đó thì gelatin cũng đã nở bạn vớt ra vắt nhẹ cho ráo nước rồi cho vô nồi khuấy. Khi gelatin tan hoàn toàn cuối cùng là cho vani vào là nhắc xuống khỏi bếp và để nguội',
            'Bước 2: Đổ khuôn',
            '- Để đổ panna cotta được đẹp mắt thì bạn cho một mứt trái cây dưới đáy ly. Sau đó lấy ra cho phần panna cotta vào rồi cho vào ngăn mát tủ lạnh.',
            '- Để cho panna cotta có hình dạng đẹp hơn thì bạn cho cái cốc lên một cái cốc khác để tạo độ nghiêng. Cho phần panna cotta vào khoảng ⅓ cốc rồi cho vào ngăn đá để cho đông lại. Sau đó lấy ra rồi cho lớp mứt trái cây vào rồi tiếp tục cho vào ngăn mát tủ lạnh. Lúc này bạn lấy cốc ra và cho cốc đứng thẳng lại rồi cho phần panna cotta vào lắp đầy cốc.',
            '- Cho panna cotta vào tủ mát tủ lạnh khoảng 4 tiếng hoặc qua đêm để cho panna cotta được đông chắc hơn.',
        ]
    }
]